#application.properties
server.port=8081
spring.application.name=EcoSolido
huggingface.api.url=https://router.huggingface.co/v1/chat/completions
huggingface.api.key=${HF_TOKEN}
# token.secret.value=${TOKEN_SECRET_VALUE}
# Clave de Itzair
token.secret.value=${TOKEN_SECRET_VALUE:mi_clave_secreta_por_defecto_muy_segura_123456789}
reniec.api.url=https://api.consultasperu.com/api/v1/query
reniec.api.token=${RENIEC_API_TOKEN}
cloudinary.url=${CLOUDINARY_URL}
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB
# Database
spring.datasource.url=jdbc:mysql://localhost:3306/EcoSolido
spring.datasource.username=root
#spring.datasource.password=MinuevaContra1

#Clave de Itzair
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Logging
logging.level.org.springframework.web=DEBUG
logging.level.com.DisenoProductos=DEBUG
# Backup - ruta de mysqldump (sobreescribir segun SO)
mysqldump.path=${MYSQLDUMP_PATH:mysqldump}
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=120000