spring.application.name=EcoSolido
huggingface.api.url=https://router.huggingface.co/v1/chat/completions
huggingface.api.key=${HF_TOKEN}
cloudinary.url=${CLOUDINARY_URL}
spring.datasource.url=jdbc:mysql://localhost:3306/EcoSolido
spring.datasource.username=root
spring.datasource.password=MinuevaContra1
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
logging.level.org.springframework.web=DEBUG
logging.level.com.DisenoProductos=DEBUG
