spring.application.name=EcoSolido
<<<<<<< HEAD
server.port=8080

huggingface.api.key=${HF_TOKEN:}
huggingface.api.url=https://router.huggingface.co/v1/chat/completions
=======
huggingface.api.key=${HF_TOKEN}
huggingface.api.url=https://router.huggingface.co/v1/chat/completions
>>>>>>> 8cb61bc0232d14d29006225ed16cb6e026b18069
