USE ecosolido;
ALTER TABLE incidencia 
MODIFY estado ENUM('PENDIENTE','EN_PROCESO','RESUELTO') DEFAULT 'PENDIENTE';
ALTER TABLE incidencia
ADD CONSTRAINT chk_estado CHECK (estado IN ('PENDIENTE', 'EN_PROCESO', 'RESUELTO'));
ALTER TABLE incidencia ADD COLUMN titulo VARCHAR(150);